- name: install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo

- name: set default nginx template
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default

- name: restart nginx service
  become: yes
  become_user: root
  become_method: sudo
  service:
    name: nginx
    state: restarted